### creates a new patient
POST http://lb-f971861c.elb.localhost.localstack.cloud:4004/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Ene266 Ejeh Kafka",
  "email": "Ene1256@gmail.com",
  "address": "21 here ave",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2025-06-06"
}
###